title: Satyarth Jaiswal
logo: "/assets/circular_headshot (2).png"
description: >-
  About me - Hi, I'm Satyarth â€” a data and marketing professional, passionate
  about solving business problems with data governance, analytics, visualisation,
  and storytelling.

theme: jekyll-theme-minimal
# theme: minimal-mistakes-jekyll
#plugins:
#  - jekyll-include-cache
#remote_theme: mmistakes/minimal-mistakes
#minimal_mistakes_skin: contrast
#links:
#  - label: Email
#    icon: fas fa-fw fa-envelope-square
#    url: mailto:jaiswal.satyarth070@gmail.com
# - label: LinkedIn
#    icon: fab fa-fw fa-linkedin-square
#    url: https://www.linkedin.com/in/satyarthj/
#google_analytics: G-RVVCTXZ7MN
#header:
#  nav: []
